server:
 servlet:
    context-path: /fr
    
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
#  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: 123456

mybatis.type-aliases-package: com.example.demo2.bean
